name: CD

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'main'

jobs:
  compile-publish:
    name: Compile and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - run: yarn install --ignore-scripts
        env:
          REGISTRY_TOKEN: ${{ secrets.PACKAGE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

      - name: Compile Contracts
        env:
          REGISTRY_TOKEN: ''
          ARBITRIUM_PRIVATE_KEY: ${{ secrets.ARBITRIUM_PRIVATE_KEY }}
        run: yarn compile

      - name: Semantic Release
        env:
          REGISTRY_TOKEN: ''
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
