name: CI

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'main'

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@primitivefinance'
          always-auth: true

      - name: Authenticate with GitHub package registry
        env:
          github_token: ${{ secrets.github_token }}
        run: echo "//npm.pkg.github.com:_authToken=${{ secrets.github_token }}" >
          ~/.npmrc

      - run: yarn install --ignore-scripts
        env:
          github_token: ${{ secrets.github_token }}

      - name: Lint
        env:
          github_token: ${{ secrets.github_token }}
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier: true
          auto_fix: true
          prettier_extensions: 'css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,sol'

      - name: Typechain
        env:
          github_token: ${{ secrets.github_token }}
        run: yarn typechain

      - name: Test
        env:
          github_token: ${{ secrets.github_token }}
        run: yarn test:fast
