name: CI

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'develop'

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
          always-auth: true

      - run: yarn install --ignore-scripts
        env:
          REGISTRY_TOKEN: ${{ secrets.PACKAGE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}

      - name: Lint
        uses: wearerequired/lint-action@v1
        env:
          REGISTRY_TOKEN: ''
        with:
          github_token: ${{ secrets.github_token }}
          prettier: true
          auto_fix: false
          continue_on_error: true
          prettier_extensions: 'css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,sol'

      - name: Test
        env:
          REGISTRY_TOKEN: ''
          ARBITRUM_PRIVATE_KEY: ${{ secrets.MOCK_PRIVATE_KEY }}
        run: yarn test
